Update .forgejo/workflows/build.yml

diff --git a/.forgejo/workflows/build.yml b/.forgejo/workflows/build.yml
--- a/.forgejo/workflows/build.yml
+++ b/.forgejo/workflows/build.yml
@@ -31,4 +31,8 @@ jobs:
 
       - name: Build
         run: |
+          if [ -z "${{ vars.GIT_URL }}" ]; then
+            echo "Error: GIT_URL variable is not set in Forgejo UI."
+            exit 1
+          fi
           make RELEASE_TYPE=Release SHARED_ONLY=OFF GIT_URL=${{ vars.GIT_URL }}
